services:
  - type: web
    name: bale-instagram-bot
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: BALE_BOT_TOKEN
        sync: false
      - key: MAKE_WEBHOOK_URL
        value: https://hook.eu1.make.com/bnels556iotmn6bgg8b25ywcxtayyawp
      - key: PUBLIC_BASE_URL
        sync: false
      - key: SELF_PING_URL
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
